# NumPy
## Practice Problems

### 1. The formula for exponential growth is `population_size = N0 *e**rt`, where `N0` is the initial population, `e` is the exponential function, `r` is the rate, and `t` is time. Using this:

1.   Set the initial population, `N0`, as 100 and the growth rate, `r`, as 0.4
2.   Use the suitable `numpy` function to generate an array of time points, `t`, which go from 0 to 10 seconds, in 0.2 second increments.
3.   Write an expression to evaluate `population_size`, which should be an array of the population size for each time point in `t`.
4.   Create a new variable called `population_size_noise`, use the same expression you wrote in parts (3), and add noise to the population at each time point. Do this by adding an expression that uses a `numpy` function to generate a random value for each time point drawn from a normal distribution of `mean=0` and `stdev=250` (i.e., population_size_noise = expression_from_part_a + expression_to_add_noise).

In [16]:
import numpy as np
t = np.arange(0, 10, 0.2)
print(t)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [24]:
N0 = 100
r = 0.4
population_size = N0*np.exp(r*t)
print(population_size)


[ 100.          108.32870677  117.3510871   127.12491503  137.71277643
  149.18246976  161.60744022  175.06725003  189.64808793  205.44332106
  222.55409285  241.08997064  261.16964734  282.92170144  306.48542033
  332.01169227  359.66397256  389.61933018  422.0695817   457.22251951
  495.30324244  536.55559711  581.24373944  629.6538261   682.09584693
  738.90560989  800.44689143  867.11376585  939.33312874 1017.56743061
 1102.31763806 1194.12644178 1293.58173155 1401.32036077 1518.0322245
 1644.46467711 1781.42731796 1929.79717555 2090.52432351 2264.63796432
 2453.25301971 2657.57726999 2878.91908792 3118.69581683 3378.44284638
 3659.82344437 3964.63940726 4294.84259788 4652.54744398 5040.04447781]


In [25]:
generator = np.random.default_rng (seed=1)
noise = generator.normal(loc=0, scale=250, size=np.shape(population_size))
print(noise)

[  86.39604802  205.40453588   82.60926905 -325.7893079   226.33896667
  111.59364309 -134.23830884  145.27952605   91.14309905   73.53312416
    7.10556033  136.67824665 -184.11352175  -40.727487   -120.52982817
  149.71155316    9.93052687  -73.11418774 -195.47711559  -64.29806015
    2.03554513  -68.90072632  323.5159536   251.68107883 -677.79061974
 -472.25331149  -43.69302301 -105.54760289   53.41074937   54.33048276
  529.45968876 -278.00519067  -94.40125178  510.69290187  161.67574905
  165.76584309 -128.50159292 -412.01879271   41.86618606   27.25352196
 -306.83801356 -170.80666545  -18.01091993 -236.18790577  -24.56749196
   23.87075687    8.89655926 -126.57291458  148.43701795  222.79173857]


In [26]:
population_size_noise = population_size + noise
population_size_noise

array([ 1.86396048e+02,  3.13733243e+02,  1.99960356e+02, -1.98664393e+02,
        3.64051743e+02,  2.60776113e+02,  2.73691314e+01,  3.20346776e+02,
        2.80791187e+02,  2.78976445e+02,  2.29659653e+02,  3.77768217e+02,
        7.70561256e+01,  2.42194214e+02,  1.85955592e+02,  4.81723245e+02,
        3.69594499e+02,  3.16505142e+02,  2.26592466e+02,  3.92924459e+02,
        4.97338788e+02,  4.67654871e+02,  9.04759693e+02,  8.81334905e+02,
        4.30522719e+00,  2.66652298e+02,  7.56753868e+02,  7.61566163e+02,
        9.92743878e+02,  1.07189791e+03,  1.63177733e+03,  9.16121251e+02,
        1.19918048e+03,  1.91201326e+03,  1.67970797e+03,  1.81023052e+03,
        1.65292573e+03,  1.51777838e+03,  2.13239051e+03,  2.29189149e+03,
        2.14641501e+03,  2.48677060e+03,  2.86090817e+03,  2.88250791e+03,
        3.35387535e+03,  3.68369420e+03,  3.97353597e+03,  4.16826968e+03,
        4.80098446e+03,  5.26283622e+03])

<details>
  <summary>Answer</summary>

  ```python
  import numpy as np

  #set initial population
  N0 = 100
  #set growth rate
  rate = 0.4
  #create array of time points 
  t = np.arange(start=0, stop=10.2, step=0.2)

  #calculate population of colony at the time points in t
  population_size = N0 * np.exp(rate*t)
  print('Population size is: ',population_size)

  #add noise to population at each time point
  population_size_noise = N0 * np.exp(rate*t) + np.random.normal(loc=0, scale=250, size=np.shape(population_size))
  print('Population size with noise is: ',population_size_noise)
  ```
</details>

### 2. Create a multiplication table for the number 6.

In [37]:
import numpy as np
x = np.arange(1, 11, 1)
y = 6
z = x * y
print(z)

[ 6 12 18 24 30 36 42 48 54 60]


In [82]:
import numpy as np
x = np.arange(1, 11, 1)
y = np.repeat(6, 10)
z = x * y
x1 = np.vstack(x)
y1 = np.vstack(y)
z1 = np.vstack(z)
for i, j, k in zip(x1, y1, z1):
    table = [str(i) + "x" + str(j) + "=" + str(k)]
    print(table)

['[1]x[6]=[6]']
['[2]x[6]=[12]']
['[3]x[6]=[18]']
['[4]x[6]=[24]']
['[5]x[6]=[30]']
['[6]x[6]=[36]']
['[7]x[6]=[42]']
['[8]x[6]=[48]']
['[9]x[6]=[54]']
['[10]x[6]=[60]']


In [84]:
rows = np.arange(1, 7)
columns = rows[:,np.newaxis]
arr = rows * columns
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

<details>
  <summary>Answer</summary>

  ```python
  rows = np.arange(1, 7)
  columns = rows[:,np.newaxis]
  arr = rows * columns
  arr
  ```
</details>

### 3. Slice `arr` to create the following two arrays:

`arr1` = [4, 12, 3]

`arr2` = [3, 19]

In [89]:
x = np.arange(1, 20, 1)
arr1 = [x[3], x[11], x[2]]
arr2 = [x[2], x[-1]]
print(arr1)
print(arr2)

[4, 12, 3]
[3, 19]


<details>
  <summary>Answer</summary>

  ```python
  arr = np.array([[4, 12, 98], [12, 11, 92], [3, 19, 60]])
  arr

  arr1 = arr[:,0]
  print(arr1)

  arr2 = arr[2,0:2]
  print(arr2)
  ```
</details>